### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by matzew**
using Strombrau project name :beers:

### CODE REVIEW

**Comment by hhiden** [comment]
If we are going with Strombrau as a name, I will change my code as well...

**Comment by matzew** [comment]
> If we are going with Strombrau as a name, I will change my code as well...

I liked your name suggestion as a first "project" name for the gateway :-)

**Comment by matzew** [comment]
@hhiden @sjwoodman should this be merged ?

**Comment by hhiden** [comment]
Yes - Ok to merge

**Pull request merged**
